### ISSUE TITLE
Exception in server tick loop crash

### ISSUE THREAD

**Issue by vadimyer** [CyberdyneCC/BigReactors#12]
Hey, running BR 0.4.3A on Thermos B55. I got this crash:

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/5/16 11:26 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: erogenousbeef/bigreactors/utils/StaticUtils$Fluids
	at erogenousbeef.bigreactors.common.block.BlockBRDevice.func_149727_a(BlockBRDevice.java:176)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:465)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:857)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: erogenousbeef.bigreactors.utils.StaticUtils$Fluids
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: ca.tcpr:Thermos:1.7.10-1614.55
	Plugins: WorldEdit, JoinCommand, Skript, DupeFixer, OpenInv, ChunkFixer, ClearLag, AutoMessage, iPAddressViewer, WorldBorder, LokiBlockerLite, BanManager, VoidSpawn, WorldGuard, AutoSaveWorld, MultiWorld, RedstoneClockDetector, Setblock, MachineGuard_Reloaded, iConomy, PermissionsEx, SQLibrary, AnimalProtect, CustomHelp, ReactionRewards, Vault, HideStream, Prism, MyWarp, ChestShop, ShoppingCartReloaded, MultiHome, ColorMe, NoobProtector, Essentials, BattleTracker, BattleArena, Scavenger, ProtocolLib, PayDay, EssentialsProtect, ModFixNG, SuperVanish, ArenaSpleef, EssentialsSpawn
	Disabled Plugins: 
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 860837456 bytes (820 MB) / 2314731520 bytes (2207 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 1 total; -Xmx12G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	IC2{2.2.817-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.817-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.X-universal.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenters-Blocks-3.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft-1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	cmd{1.4} [Custom Music Discs] (Custom Music Discs-1.4 Server.jar) 
	UCHIJAAAA	DragonsRadioMod{1.7.1} [Dragon's Radio Mod] (Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.32_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.32_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAAAA	EventHelper{1.6} [EventHelper] (EventHelper-1.6.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	Forestry{4.2.10.58} [Forestry for Minecraft] (forestry_1.7.10-4.2.10.58.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	gvc{0.6.1} [�aGliby's�f Voice Chat Mod] (GlibysVC-1.7.10-0.6.2a.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	GraviSuiteReloaded{1.7.10-0.9.1} [GraviSuiteReloaded] (GraviSuite_Reloaded-1.7.10-0.9.1.jar) 
	UCHIJAAAA	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UCHIJAAAA	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.5} [Immersive Engineering] (ImmersiveEngineering-0.7.5.jar) 
	UCHIJAAAA	IronChest{6.0.41.729} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail, agricraft, enderio, erebus, extrautilities, growthcraft, harvestcraft, immersiveengineering, magicalcrops, natura, plantmegapack, witchery
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 33 / 100; [EntityPlayerMP['I0debil'/1493, l='world', x=8947.77, y=63.00, z=3562.78](I0debil at 8947.769899714162,63.0,3562.776252599156), EntityPlayerMP['krivedka'/4020, l='world', x=-1662.77, y=65.00, z=-1595.83](krivedka at -1662.7743664439092,65.0,-1595.8328746344218), EntityPlayerMP['Real'/6333, l='world', x=-2209.27, y=85.00, z=5035.65](Real at -2209.270132458333,85.0,5035.648222160443), EntityPlayerMP['prostochok12'/6380, l='world', x=-546.81, y=73.00, z=100.06](prostochok12 at -546.8085189345511,73.0,100.06170600202302), EntityPlayerMP['cashman'/21519, l='world', x=-941.55, y=64.00, z=-1511.38](cashman at -941.5539310314034,64.0,-1511.38305903293), EntityPlayerMP['smeshka'/90920, l='world', x=7450.39, y=68.11, z=6459.66](smeshka at 7450.390617856563,68.1116330269739,6459.656032369676), EntityPlayerMP['Ve1rT'/228421, l='world', x=-1709.17, y=69.00, z=-4552.58](Ve1rT at -1709.17252694663,69.0,-4552.577189752467), EntityPlayerMP['Sheldo'/414696, l='world', x=-16.49, y=140.00, z=2201.70](Sheldo at -16.488344010372337,140.0,2201.697596561301), EntityPlayerMP['masha1love'/605399, l='world', x=2130.86, y=69.00, z=-15.86](masha1love at 2130.856179686544,69.0,-15.864420493853537), EntityPlayerMP['Vol4ica'/614343, l='world', x=-3350.75, y=71.00, z=5959.57](Vol4ica at -3350.7543354818354,71.0,5959.573040760308), EntityPlayerMP['Aza7777'/622473, l='world', x=1267.59, y=63.00, z=-2748.58](Aza7777 at 1267.5880351966964,63.0,-2748.581554859883), EntityPlayerMP['Miha91137'/647362, l='world', x=-1662.41, y=65.00, z=-1596.74](Miha91137 at -1662.406940177285,65.0,-1596.7354749009935), EntityPlayerMP['DjFess'/665267, l='world', x=3756.30, y=65.88, z=-6325.72](DjFess at 3756.300000011921,65.875,-6325.721188954313), EntityPlayerMP['danielr7'/755574, l='world', x=-917.96, y=63.00, z=122.22](danielr7 at -917.9572164409752,63.0,122.22080037282333), EntityPlayerMP['Owl'/755844, l='world', x=-2391.00, y=66.00, z=537.30](Owl at -2391.0,66.0,537.3000000119209), EntityPlayerMP['Glafira'/757611, l='world', x=-5010.20, y=15.00, z=-3779.22](Glafira at -5010.200152480102,15.0,-3779.223718563249), EntityPlayerMP['CarlsoonMD'/764526, l='world', x=-5408.00, y=63.00, z=2931.47](CarlsoonMD at -5407.996570660468,63.0,2931.4703455293115), EntityPlayerMP['unLuckyGamer'/769603, l='world', x=249.30, y=59.00, z=-289.75](unLuckyGamer at 249.30000001192093,59.0,-289.75267294720186), EntityPlayerMP['TsurikMAN'/771684, l='world', x=-14.16, y=130.00, z=2195.63](TsurikMAN at -14.156457816330198,130.0,2195.626112708214), EntityPlayerMP['Kardinal18'/790404, l='world', x=-444.54, y=64.00, z=355.99](Kardinal18 at -444.5401325929088,64.0,355.9935191004235), EntityPlayerMP['KanYouMan'/807047, l='world', x=-779.88, y=150.00, z=-3585.02](KanYouMan at -779.8811080415596,150.0,-3585.0190959544348), EntityPlayerMP['w0land'/819997, l='world', x=-1467.43, y=63.00, z=2100.76](w0land at -1467.4313761885649,63.0,2100.7577231577684), EntityPlayerMP['MbICb'/886110, l='world', x=4168.83, y=64.00, z=-5285.13](MbICb at 4168.828332930657,64.0,-5285.125637711244), EntityPlayerMP['Sorry'/887248, l='world', x=-1823.55, y=65.38, z=2683.88](Sorry at -1823.5455178059813,65.37889443243856,2683.880030506714), EntityPlayerMP['djek87'/889411, l='world', x=3849.18, y=66.00, z=-7172.58](djek87 at 3849.182592626656,66.0,-7172.580596716607), EntityPlayerMP['DoktoR0Xayc'/908099, l='DIM1', x=-264.23, y=53.99, z=88.14](DoktoR0Xayc at -264.2294920102046,53.98510056979053,88.1446356656169), EntityPlayerMP['DikkeryDok'/797941, l='world', x=-1499.64, y=69.00, z=3928.79](DikkeryDok at -1499.641970639933,69.0,3928.791545693783), EntityPlayerMP['DreAmeR'/922487, l='world', x=2078.24, y=69.00, z=-23.28](DreAmeR at 2078.24076514183,69.0,-23.27544045813095), EntityPlayerMP['Mozart'/379198, l='world', x=-933.14, y=65.00, z=-1517.07](Mozart at -933.1399126236661,65.0,-1517.071235283655), EntityPlayerMP['LongCake'/936773, l='DIM-1', x=119.91, y=138.00, z=1226.24](LongCake at 119.91392688031264,138.0,1226.2447822995823), EntityPlayerMP['CarlsberG'/937063, l='world', x=-1928.27, y=71.59, z=-1238.38](CarlsberG at -1928.2683764285323,71.5900000333786,-1238.3831996719277), EntityPlayerMP['AVEL'/963024, l='DIM-1', x=-303.32, y=72.88, z=95.15](AVEL at -303.3167841363901,72.875,95.15427916280078), EntityPlayerMP['Vetas'/963972, l='car', x=147.93, y=100.11, z=194.17](Vetas at 147.92926300471558,100.11035392227929,194.16845682028546)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

What to look for?

**Comment by XFactHD** [comment]
Can you reproduce this on a normal minecraft forge server and/or in single player

**Comment by Robotia** [comment]
This error should not occur unless Java is unable to access the JAR file. Did you replace the jar while your server is running?

**Comment by vadimyer** [comment]
Hmm, probably. This never happened before, or again. I'm now running 0.4.5B latest (but without your class fixes I suppose). So far except the problem with fuel vanishing, everything seems fine.

**Comment by Robotia** [comment]
Alright, I'll go ahead and close it. :ok_hand:
